print ('Olá mundo')
print ('Olá planeta')
print ('Tudo bem')
print('Boa noite')
print('Tudo ok?')
print('Beleza!')
print ('Tudo certo?')
print ('Quando vai ser?')
print ('Boa tarde')
print ('Alguma duvida')